### ISSUE TITLE
About MoFREAK

### ISSUE THREAD

**Issue by CHienSF** [craig08/MoFREAK_Hardware#1]
Dear Craig Chi

I just started my journey for the MoFREAK. I have been using almost 4 days for fitting the bugs for the MoFREAK program that I obtained from ChrisWithen. Now, I have the last issue i.e.,  #include "qimage.h". I find no such a header file in github. I have spent four hours this afternoon searching this file but failed to get it. If you have the file would you mind sending me a copy? Do I need to install the software related to Qt?

I just study the paper one week ago so that I have very little understanding of the MoFREAK. Your kind assistance is very much needed actually.

Look forwards to hearing from you.

Thanks
Mr. Chien

**Comment by craig08** [comment]
I am sorry to tell you I don't have "qimage.h" file either. I forked this project from Chris Whiten and I didn't see that the main MoFREAK program requires "qimage.h" to compile since I didn't include OpenCVToQtInterfacing.h in main.cpp. If you cannot find the file online, I suggest you ask Mr. Whiten for help. Thanks!

**Comment by CHienSF** [comment]
Hi Craig Chi

Thank you very much for your explanation. 
There is one issue in the main program that I can't understand in which the Visual Studio 2017 shows clustering.buildDataFromMoFREAK(mofreak->getMoFREAKFeatures(), false, false) has an error due to mofreak->getMoFREAKFeatures(). However, if I set std::deque y = mofreak->getMoFREAKFeatures() and then pass y to the function, it doesn't show anymore. But, I don't think it is a proper way. So, I add one more statement after the function call, i.e., (mofreak->getMoFREAKFeatures() =y. Do you know why the function cannot accept the argument mofreak->getMoFREAKFeatures()?

Your work was the enhancement version. I am interested to know whether you either enhance the code flows so that it can speed up the computing process or improve the detection accuracy. If you have a paper published, would you mind sending me a copy? Since you put the MoFREAK_Hardware I expect you applying the FREAK algorithm for running a human action detection project, I may guess wrongly. TQ.

**Comment by craig08** [comment]
@MIMOS-Chien I guess that's because `clustering.buildDataFromMoFREAK()` function requires a reference of a deque. When you pass by `mofreak->getMoFREAKFeatures()`, it is a **rvalue**. However, if it requires a reference of the object, you should pass in an **lvalue**. I guess the older versions of Visual Studio have some magic to work around this so they won't report the error.

I do have a paper, but it is unfortunately not be published publicly. I'll send it to your email.
